version: "3.6"

services:
  simplytranslate:
    container_name: simplytranslate
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - ADDRESS=0.0.0.0:5000
      - GOOGLETRANSLATE_ENABLE=true
      - ICIBA_ENABLE=true
      - REVERSO_ENABLE=true